-- Restore snapshot taken 2026-09-29T07:01:09+01:00 from 10.50.1.1/klas
-- pra ids 220244,220245 (TEMP-151036, TEMP-151039) + PropID_Master prop_id 187647,187648

SET IDENTITY_INSERT dbo.pra ON;
INSERT INTO dbo.pra ([id], [mlsFNo], [kangisFileNo], [NewKANGISFileno], [title_type], [transaction_type], [transaction_date], [serialNo], [pageNo], [volumeNo], [regNo], [instrument_type], [period], [period_unit], [Assignor], [Assignee], [Mortgagor], [Mortgagee], [Surrenderor], [Surrenderee], [Lessor], [Lessee], [Grantor], [Grantee], [property_description], [location], [streetName], [house_no], [districtName], [plot_no], [lgsaOrCity], [layout], [schedule], [created_at], [updated_at], [deleted_at], [created_by], [updated_by], [source], [tp_no], [lpkn_no], [approved_plan_no], [plot_size], [date_recommended], [date_approved], [lease_begins], [lease_expires], [metric_sheet], [is_caveated], [caveated_comment], [caveat_id], [fileno], [date_migrated], [migrated_by], [prop_id], [date_created], [migration_source], [land_use], [comments], [assignment_date], [surrender_date], [revoked_date], [regranted_from], [date_expired], [remarks], [oldKNNo], [test_control], [related_file_number], [deeds_date], [deeds_time], [temp_fileno], [Releasor], [Releasee], [Donor], [Donee], [party_1], [party_2], [party_3], [Mortgagor_2], [Vendor], [Purchaser], [is_mapped], [party_4], [Mortgagor_3], [Surrenderor_2], [op_type], [instrument_capture_id], [op_serial_number], [source_pra_id], [is_deleted], [rofo_number], [system_source], [merger_group_id], [is_merger_op], [is_subdivided], [op_count], [source_op_table], [source_op_id], [parent_prop_id], [resolved_fileno], [title_status], [title_status_type], [title_status_remark], [status], [reg_date], [reg_time], [party_5], [op_batch], [purpose], [purpose_id], [land_use_source], [ancestral_prop_id], [cofo_type], [instrument_category], [instrument_subtype], [consideration_amount], [receipt_no])
VALUES (N'220244', NULL, NULL, NULL, NULL, N'Occupancy Permit (OP) - OP Resettlement', N'2026-09-29', N'66', N'66', N'259', N'66/66/259', N'Occupancy Permit (OP)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'Kano State Government', N'TEST 123', N'349, YARGAYA ST, TAKAI TOWN, Warawa, Wudil, Kano', N'TAKAI TOWN', NULL, N'49', NULL, N'349', N'Warawa, Wudil', NULL, NULL, N'2026-09-29 06:55:20.267', N'2026-09-29 06:55:20.267', NULL, N'1', N'1', N'Occupancy Permit (OP)', NULL, N'227', NULL, N'NEVADA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'TEMP-151036', NULL, NULL, N'187647', NULL, NULL, N'COMMERCIAL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2026-05-22', N'04:18', N'TEMP-151036', NULL, NULL, NULL, NULL, N'Kano State Government', N'TEST 123', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'OP Resettlement', NULL, N'40155', NULL, N'0', NULL, NULL, NULL, N'0', N'0', NULL, NULL, NULL, NULL, N'TEMP-151036', N'0', NULL, NULL, N'Active', N'2026-05-22', N'04:18', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
SET IDENTITY_INSERT dbo.pra OFF;

SET IDENTITY_INSERT dbo.pra ON;
INSERT INTO dbo.pra ([id], [mlsFNo], [kangisFileNo], [NewKANGISFileno], [title_type], [transaction_type], [transaction_date], [serialNo], [pageNo], [volumeNo], [regNo], [instrument_type], [period], [period_unit], [Assignor], [Assignee], [Mortgagor], [Mortgagee], [Surrenderor], [Surrenderee], [Lessor], [Lessee], [Grantor], [Grantee], [property_description], [location], [streetName], [house_no], [districtName], [plot_no], [lgsaOrCity], [layout], [schedule], [created_at], [updated_at], [deleted_at], [created_by], [updated_by], [source], [tp_no], [lpkn_no], [approved_plan_no], [plot_size], [date_recommended], [date_approved], [lease_begins], [lease_expires], [metric_sheet], [is_caveated], [caveated_comment], [caveat_id], [fileno], [date_migrated], [migrated_by], [prop_id], [date_created], [migration_source], [land_use], [comments], [assignment_date], [surrender_date], [revoked_date], [regranted_from], [date_expired], [remarks], [oldKNNo], [test_control], [related_file_number], [deeds_date], [deeds_time], [temp_fileno], [Releasor], [Releasee], [Donor], [Donee], [party_1], [party_2], [party_3], [Mortgagor_2], [Vendor], [Purchaser], [is_mapped], [party_4], [Mortgagor_3], [Surrenderor_2], [op_type], [instrument_capture_id], [op_serial_number], [source_pra_id], [is_deleted], [rofo_number], [system_source], [merger_group_id], [is_merger_op], [is_subdivided], [op_count], [source_op_table], [source_op_id], [parent_prop_id], [resolved_fileno], [title_status], [title_status_type], [title_status_remark], [status], [reg_date], [reg_time], [party_5], [op_batch], [purpose], [purpose_id], [land_use_source], [ancestral_prop_id], [cofo_type], [instrument_category], [instrument_subtype], [consideration_amount], [receipt_no])
VALUES (N'220245', NULL, NULL, NULL, NULL, N'Occupancy Permit (OP) - OP Resettlement', N'2026-09-29', N'426', N'426', N'203', N'426/426/203', N'Occupancy Permit (OP)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'Kano State Government', N'ALAYNA SAUER', N'457, BELLO KANO TERRACE, HOTORO G, Bagwai, Bebeji, Bichi, Bunkure, Dambatta, Dawakin Kudu, Doguwa, Gabasawa, Garko, Garun Mallam, Gezawa, Gwale, Gwarzo, Kano Municipal, Kiru, Kura, Madobi, Minjibir, Rogo, Shanono, Tofa, Tudun Wada, Ungogo, Kano', N'HOTORO G', NULL, N'520', NULL, N'457', N'Bagwai, Bebeji, Bichi, Bunkure, Dambatta, Dawakin Kudu, Doguwa, Gabasawa, Garko, Garun Mallam, Gezawa, Gwale, Gwarzo, Kano Municipal, Kiru, Kura, Madobi, Minjibir, Rogo, Shanono, Tofa, Tudun Wada, Ungogo', NULL, NULL, N'2026-09-29 06:57:24.972', N'2026-09-29 06:57:24.972', NULL, N'1', N'1', N'Occupancy Permit (OP)', NULL, N'35', NULL, N'CONNECTICUT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'TEMP-151039', NULL, NULL, N'187648', NULL, NULL, N'RESIDENTIAL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2026-02-02', N'20:09', N'TEMP-151039', NULL, NULL, NULL, NULL, N'Kano State Government', N'ALAYNA SAUER', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'OP Resettlement', NULL, N'644', NULL, N'0', NULL, NULL, NULL, N'0', N'0', NULL, NULL, NULL, NULL, N'TEMP-151039', N'0', NULL, NULL, N'Active', N'2026-02-02', N'20:09', NULL, NULL, N'HIGH DENSITY', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
SET IDENTITY_INSERT dbo.pra OFF;

SET IDENTITY_INSERT dbo.PropID_Master ON;
INSERT INTO dbo.PropID_Master ([id], [prop_id], [primary_file_number], [mlsFNo], [kangisFileNo], [NewKANGISFileno], [temp_fileno], [source_table], [source_record_id], [status], [notes], [created_at], [updated_at], [primary_file_number_norm], [mlsFNo_norm], [kangisFileNo_norm], [NewKANGISFileno_norm], [temp_fileno_norm])
VALUES (N'192530', N'187647', N'TEMP-151036', NULL, NULL, NULL, N'TEMP-151036', NULL, NULL, N'active', NULL, N'2026-09-29 06:55:20', N'2026-09-29 06:55:20', N'TEMP-151036', NULL, NULL, NULL, N'TEMP-151036');
SET IDENTITY_INSERT dbo.PropID_Master OFF;

SET IDENTITY_INSERT dbo.PropID_Master ON;
INSERT INTO dbo.PropID_Master ([id], [prop_id], [primary_file_number], [mlsFNo], [kangisFileNo], [NewKANGISFileno], [temp_fileno], [source_table], [source_record_id], [status], [notes], [created_at], [updated_at], [primary_file_number_norm], [mlsFNo_norm], [kangisFileNo_norm], [NewKANGISFileno_norm], [temp_fileno_norm])
VALUES (N'192531', N'187648', N'TEMP-151039', NULL, NULL, NULL, N'TEMP-151039', NULL, NULL, N'active', NULL, N'2026-09-29 06:57:25', N'2026-09-29 06:57:25', N'TEMP-151039', NULL, NULL, NULL, N'TEMP-151039');
SET IDENTITY_INSERT dbo.PropID_Master OFF;

