@echo off
setlocal enabledelayedexpansion
REM Generated by scripts\deploy\make-deploy.ps1 - runs ONLY this release's migrations.
REM A bare "php artisan migrate" would also run older pending migrations.

set "PROJECT=C:\xampp\htdocs\klas"
set "PHP=C:\xampp\php\php.exe"

if not exist "%PROJECT%\artisan" echo   ERROR: no artisan at %PROJECT% & goto :end
if not exist "%PHP%" echo   ERROR: no php.exe at %PHP% & goto :end
cd /d "%PROJECT%"
set FAILED=0
echo.
call :run 2026_08_10_100000_add_party_2_gender_to_instrument_capture_table.php
echo.
if "!FAILED!"=="0" (echo   All migrations completed.) else (echo   *** !FAILED! FAILED - read the errors above. ***)
goto :end

:run
echo   -^> %~1
REM Running before the files are copied gives a bare Laravel stack trace.
REM Say what is actually wrong instead.
if not exist "%PROJECT%\database\migrations\%~1" (
  echo      NOT ON PRODUCTION YET - copy the release folders into
  echo      %PROJECT% first, then re-run this script.
  set /a FAILED+=1
  echo.
  exit /b 0
)
"%PHP%" artisan migrate --force --path=database/migrations/%~1
if errorlevel 1 (set /a FAILED+=1 & echo      FAILED)
echo.
exit /b 0

:end
echo.
pause
